export const UPDATE_PRODUCTS = "UPDATE_PRODUCTS";
export const UPDATE_POST = "UPDATE_POST"
export const ADD_TO_CART = "ADD_TO_CART";
export const ADD_MULTIPLE_TO_CART = "ADD_MULTIPLE_TO_CART";
export const REMOVE_FROM_CART = "REMOVE_FROM_CART";
export const UPDATE_CURRENT_TAG = "UPDATE_CURRENT_TAG";
export const UPDATE_TAGS = "UPDATE_TAGS";
